### ISSUE TITLE
Lost progress when stopping the docker container

### ISSUE THREAD

**Issue by broizter** [mbround18/valheim-docker#30] opened 2021-02-10 10:14 UTC
I ran a simple "docker stop valheim" and "docker start valheim" and it stopped the container within maybe 5 seconds which should indicate it was done cleanly, but when it was started again the server had rolled back 30 minutes or so. I'm sure you need more information to debug this so let me know what that would be. This was a pretty serious bug that made me a bit scared.

Edit: It's possible this problem has to do with the actual server software not anything to do with the docker container. It seems it commits changes to the world to disk very infrequently, and when you shut down the server software it doesnt force a save.

**Comment by waschinski** [comment] 2021-02-10 13:28
I actually think you are supposed to exec `odin stop` inside the container before stopping the container itself.

**Comment by broizter** [comment] 2021-02-10 13:32
I haven't tried that, but I guess it would make sense! If that is the solution then I guess the docker container should run that command automatically when shutting down? Because it's easy to forget if you need to reboot the server or whatever else it may be.

**Comment by Shuro** [comment] 2021-02-10 15:16
Normally it should do an graceful exit, aka ctrl + c, to the running stuff. But there was also a patch for the server in 0.143.1 of the server files, maybe that helps.

**Comment by mbround18** [comment] 2021-02-10 16:30
If you must stop the server for now, I suggest you use htop to send SIGINT to the server process while I work on a fix

**Comment by mbround18** [comment] 2021-02-10 18:50
Fix for this is live on `:latest` and working on my production servers. Would someone mind giving it a whirl to confirm?

![image](https://user-images.githubusercontent.com/12646562/107556228-61338e80-6b95-11eb-8086-3ee61144ec79.png)

**Comment by mbround18** [comment] 2021-02-11 03:34
Suhhhweeeeeeet! Confirmed on my kubernetes cluster. Closing this issue, thank you @spion06 for the help <3
![image](https://user-images.githubusercontent.com/12646562/107599912-5f8eb880-6bdf-11eb-9f95-7e989189d825.png)

**Closed** 2021-02-11 03:34 UTC
Labels: bug, odin

**Comment by Yotimoto** [comment] 2022-04-11 20:35
I just had this issue when I ran `docker-compose down`. Progress seems to be saved reliably when I trigger a save via console commands.
