### ISSUE TITLE
Incompatible version error

### ISSUE THREAD

**Issue by Gengar-sama** [mbround18/valheim-docker#763] opened 2023-12-14 20:42 UTC
I have just had an update to Valheim, I was unable to log in due to a version mismatch.

I have tried downing and upping the container but no update.

Went so far as to prune the image and reload the container in a completely different folder so as to generate a new world seed and am having the same issue.

Logs from my last down/ up are below, my client is running v 0.217.38 the server is running v 0.217.31

```
[Valheim][root] : ###########################################################################
[Valheim][root] : Valheim Server - Thu Dec 14 08:35:46 PM GMT 2023
[Valheim][root] : Initializing your container...
[Valheim][root] : ###########################################################################
[Valheim][root] : Switching UID and GID
[Valheim][root] : usermod: no changes
[Valheim][root] :
Configuring Preset Env
Preset Env Configured
[Valheim][root] : Auto Update Enabled...
[Valheim][root] : Auto Update Schedule: 0 1 * * *
[Valheim][root] : Auto Backup Enabled...
[Valheim][root] : Auto Backup Schedule: */15 * * * *
[Valheim][root] : Setting up file systems
[Valheim][root] : Navigating to steam home...
[Valheim][root] : Launching as steam...
[Valheim][steam]: ###########################################################################
[Valheim][steam]: Valheim Server - Thu Dec 14 08:35:46 PM GMT 2023
[Valheim][steam]: STEAM_UID 1000 - STEAM_GUID 1000
[Valheim][steam]: Installing Valheim via odin 2.1.0...
[Valheim][steam]: ###########################################################################
[Valheim][steam]: Variables loaded.....
[Valheim][steam]: Port: 2456
[Valheim][steam]: Name: The_Hive_Mind
[Valheim][steam]: World: Dedicated
[Valheim][steam]: Public: 0
[Valheim][steam]: With Crossplay: 1
[Valheim][steam]: Password: (REDACTED)
[Valheim][steam]: Preset:
[Valheim][steam]: Modifiers:
[Valheim][steam]: Set Key:
[Valheim][steam]: Has Webhook: true
[Valheim][steam]: Auto Update: 1
[Valheim][steam]: Auto Backup: 1
[Valheim][steam]: Auto Backup On Update: 1
[Valheim][steam]: Auto Backup On Shutdown: 1
[Valheim][steam]: Auto Backup Pause With No Players: 0
[Valheim][steam]: Auto Backup Pause With Players:
[Valheim][steam]: Auto Backup Remove Old: 1
[Valheim][steam]: Auto Backup Days To Live: 3
[Valheim][steam]: Auto Backup Nice Level:
[Valheim][steam]: Update On Startup: 0
[Valheim][steam]: Mods:
[Valheim][steam]: ###########################################################################
[Valheim][steam]: Running Install...
[Valheim][steam]: Skipping install process, looks like valheim_server is already installed :)
[Valheim][steam]: Initializing Variables....
[ODIN][INFO]  - Successfully written /home/steam/valheim/config.json
[Valheim][steam]: Checking for TYPE flag
[Valheim][steam]: Found Type Vanilla
[Valheim][steam]: Running with Vanilla Valheim <3
[Valheim][steam]: Starting server...
[ODIN][INFO]  - Setting up start scripts...
[ODIN][INFO]  - Sending discord notification <3
[ODIN][INFO]  - [Start Running]: Webhook message sent successfully!
[ODIN][INFO]  - Looking for burial mounds...
[ODIN][INFO]  - Executing: /home/steam/valheim/valheim_server.x86_64 .....
[ODIN][INFO]  - Password found, adding password flag.
[ODIN][INFO]  - Launching with Crossplay! <3
[ODIN][INFO]  - Launching Command...
[ODIN][INFO]  - Everything looks good! Running normally!
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-allocator-temp-initial-block-size-main=262144"
    "memorysetup-allocator-temp-initial-block-size-worker=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
Mono path[0] = '/home/steam/valheim/valheim_server_Data/Managed'
Mono config path = '/home/steam/valheim/valheim_server_Data/MonoBleedingEdge/etc'
Preloaded 'libparty.so'
Preloaded 'libsteam_api.so'
[Physics::Module] Initialized MultithreadedJobDispatcher with 3 workers.
Initialize engine version: 2022.3.12f1 (4fe6e059c7ef)
[Subsystems] Discovering subsystems at path /home/steam/valheim/valheim_server_Data/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0; jobified=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly
- Loaded All Assemblies, in  0.109 seconds
- Finished resetting the current domain, in  0.002 seconds
ERROR: Shader Sprites/Default shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Sprites/Mask shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader TextMeshPro/Mobile/Distance Field shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'TextMeshPro/Distance Field' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader TextMeshPro/Distance Field shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'TextMeshPro/Distance Field' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader GUI/Text Shader shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
There is no texture data available to upload.
UnloadTime: 0.965670 ms
12/14/2023 20:35:47: Fetching PlatformPrefs 'GuiScale' before loading defaults
12/14/2023 20:35:47: Fetching PlatformPrefs 'GuiScale' before loading defaults
12/14/2023 20:35:47: Starting to load scene:start
Couldn't create a Convex Mesh from source mesh "default" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
Couldn't create a Convex Mesh from source mesh "default" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
[Valheim][steam]: Herding Graydwarfs...
==> /home/steam/valheim/logs/valheim_server.log <==
[ODIN][ERROR] - Error: unable to set group, errno 1

==> /home/steam/valheim/logs/valheim_server.err <==

==> /home/steam/valheim/logs/output.log <==

==> /home/steam/valheim/logs/auto-update.out <==

==> /home/steam/valheim/logs/auto-backup.out <==
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
ERROR: Shader Legacy Shaders/Particles/Additive shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader TextMeshPro/Distance Field (Surface) shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Legacy Shaders/VertexLit shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Standard shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Unlit/Color shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Legacy Shaders/Particles/Alpha Blended shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard (Specular setup)' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Standard (Specular setup) shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Standard (Specular setup)' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Legacy Shaders/Particles/Alpha Blended Premultiply shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Lux Lit Particles/ Bumped shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Autodesk Interactive' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Autodesk Interactive shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Autodesk Interactive' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
Shader 'Lux Lit Particles/ Tess Bumped': fallback shader 'Lux Lit Particles/ Bumped Smoke' not found
WARNING: Shader Unsupported: 'Lux Lit Particles/ Tess Bumped' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
ERROR: Shader Lux Lit Particles/ Tess Bumped shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
WARNING: Shader Unsupported: 'Lux Lit Particles/ Tess Bumped' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
No mesh data available for mesh default on particle system Carapace. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system vfx_Firework_Rocket_Red. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system vfx_Firework_Rocket_Purple. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system vfx_Firework_Rocket_Blue. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system Carapace. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system Wings. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system Legs. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system BodyGibs. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system eyes. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system Carapace. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system Head. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system shockwave_plane. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system BodyGibs (2). Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system Carapace. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system vfx_RockHit (2). Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system Eggs. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system vfx_Firework_Rocket_Yellow. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system Legs. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system BodyGibs (1). Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system vfx_Firework_Rocket_Cyan. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system Carapace. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system vfx_RockHit (2). Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system Carapace_ass. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system Wings. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system vfx_Firework_Rocket. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system Legs. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system vfx_Firework_Rocket_Green. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system Carapace_ass. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system Wings. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
No mesh data available for mesh default on particle system Legs. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
UnloadTime: 7.666465 ms
Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
HDR Render Texture not supported, disabling HDR on reflection probe.
12/14/2023 20:35:52: Setting -savedir to: /home/steam/.config/unity3d/IronGate/Valheim
12/14/2023 20:35:52: Get create world Dedicated
12/14/2023 20:35:52: Using environment steamid 892970
12/14/2023 20:35:52: Using steam APPID:892970
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Setting breakpad minidump AppID = 892970
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded no]
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
12/14/2023 20:35:52: Server ID 90071992547409920
12/14/2023 20:35:52: Authentication:k_ESteamNetworkingAvailability_Waiting
12/14/2023 20:35:52: Steam game server initialized
12/14/2023 20:35:52: Using default prefs
12/14/2023 20:35:52: Valheim version: l-0.217.31 (network version 18)
12/14/2023 20:35:52: Worldgenerator version setup:2
12/14/2023 20:35:52: Console: Valheim l-0.217.31 (network version 18)
12/14/2023 20:35:52: Console:
12/14/2023 20:35:52: Console: type "help" - for commands
12/14/2023 20:35:52: Console:
12/14/2023 20:35:52: Render threading mode:SingleThreaded
12/14/2023 20:35:52: Set button "CamZoomIn" to None!
12/14/2023 20:35:52: Set button "CamZoomOut" to None!
12/14/2023 20:35:52: Set button "CamZoomIn" to None!
12/14/2023 20:35:52: Set button "CamZoomOut" to None!
12/14/2023 20:35:52: Missing audio clip in music respawn
ERROR: Shader UI/Default shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
12/14/2023 20:35:52: Builder started
12/14/2023 20:35:52: Loaded localization file #0 - 'localization' language: 'English'
12/14/2023 20:35:52: Loaded localization file #1 - 'localization_extra' language: 'English'
12/14/2023 20:35:52: Loaded localization file #2 - 'heightmap_message' language: 'English'
12/14/2023 20:35:52: Loaded localization file #3 - 'localization_hildir' language: 'English'
12/14/2023 20:35:52: Loaded localization file #4 - 'localization_emotes' language: 'English'
12/14/2023 20:35:52: Sending PlayFab login request (attempt 1)
12/14/2023 20:35:52: Login postponed until ID has been set.
The shader Hidden/Dof/DepthOfFieldHdr (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) is not supported on this platform!
The image effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) has been disabled as it's not supported on the current platform.
The shader Hidden/SunShaftsComposite (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) is not supported on this platform!
The shader Hidden/SimpleClear (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) is not supported on this platform!
The image effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) has been disabled as it's not supported on the current platform.
12/14/2023 20:35:52: Starting music menu
ERROR: Shader TextMeshPro/Sprite shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
Unloading 52 unused Assets to reduce memory usage. Loaded Objects now: 153580.
Total: 95.782369 ms (FindLiveObjects: 9.903226 ms CreateObjectMapping: 13.389708 ms MarkObjects: 72.133945 ms  DeleteObjects: 0.354770 ms)

ERROR: Shader Hidden/RadialSegementShader shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
ERROR: Shader Hidden/RadialCutoutShader shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
There is no texture data available to upload.
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 15.224039 ms
HDR Render Texture not supported, disabling HDR on reflection probe.
HDR Render Texture not supported, disabling HDR on reflection probe.
12/14/2023 20:35:53: Using default prefs
12/14/2023 20:35:53: Console: Valheim l-0.217.31 (network version 18)
12/14/2023 20:35:53: Console:
12/14/2023 20:35:53: Console: type "help" - for commands
12/14/2023 20:35:53: Console:
12/14/2023 20:35:53: isModded: False
12/14/2023 20:35:53: Zonesystem Awake 156690
12/14/2023 20:35:53: DungeonDB Awake 156690
12/14/2023 20:35:53: Registering lobby
12/14/2023 20:35:53: PlayFab custom ID set to "PlayFab_The_Hive_Mind_2456_0785124b795ff24a980d03026558887b"
12/14/2023 20:35:53: Sending PlayFab login request (attempt 2)
12/14/2023 20:35:53: Worldgenerator version setup:2
12/14/2023 20:35:56: Audioman already exist, destroying self
12/14/2023 20:35:56: Console: /w [text] - Whisper
12/14/2023 20:35:56: Console: /s [text] - Shout
12/14/2023 20:35:56: Console: /die - Kill yourself
12/14/2023 20:35:56: Console: /resetspawn - Reset spawn point
12/14/2023 20:35:56: Console: /[emote]
12/14/2023 20:35:56: Console: Emotes: wave, sit, challenge, cheer, nonono, thumbsup, point, blowkiss, bow, cower, cry, despair, flex, comehere, headbang, kneel, laugh, roar, shrug, dance
12/14/2023 20:35:56: Console:
12/14/2023 20:35:56: PlayFab logged in as "PlayFab_The_Hive_Mind_2456_0785124b795ff24a980d03026558887b"
12/14/2023 20:35:56: PlayFab local entity ID is 14C4E5C9D5EBB55C
12/14/2023 20:35:56: New session server "The_Hive_Mind" that has join code , now 0 player(s)
12/14/2023 20:35:56: Register PlayFab server "The_Hive_Mind" with IP 154.61.58.205:2456
12/14/2023 20:35:56: Server 'The_Hive_Mind' begin PlayFab create and join network for server
Unloading 105 unused Assets to reduce memory usage. Loaded Objects now: 152970.
Total: 64.325980 ms (FindLiveObjects: 7.966735 ms CreateObjectMapping: 14.491749 ms MarkObjects: 40.872675 ms  DeleteObjects: 0.993541 ms)

There is no texture data available to upload.
There is no texture data available to upload.
There is no texture data available to upload.
There is no texture data available to upload.
There is no texture data available to upload.
There is no texture data available to upload.
There is no texture data available to upload.
There is no texture data available to upload.
There is no texture data available to upload.
12/14/2023 20:36:03: Zonesystem Start 156690
12/14/2023 20:36:03: Added 3 locations, 0 vegetations, 0 environments, 0 biome env-setups, 0 clutter  from locations_cp1
12/14/2023 20:36:03: Added 1 locations, 0 vegetations, 2 environments, 0 biome env-setups, 0 clutter  from locations_mountaincaves
12/14/2023 20:36:03: Added 27 locations, 25 vegetations, 5 environments, 1 biome env-setups, 3 clutter  from locations_mistlands
12/14/2023 20:36:03: Added 4 locations, 0 vegetations, 1 environments, 0 biome env-setups, 0 clutter  from locations_hildir
12/14/2023 20:36:03: DungeonDB Start 156690
12/14/2023 20:36:04: ZRpc timeout set to 30s
12/14/2023 20:36:04: ZNET START
12/14/2023 20:36:04: Load world: Dedicated (Dedicated)
12/14/2023 20:36:04: Loading 328502 zdos, my sessionID: 2157965536, data version: 33
12/14/2023 20:36:04: Creating ZDOs
12/14/2023 20:36:04: Loading in ZDOs
12/14/2023 20:36:05: Adding to Dictionary
12/14/2023 20:36:05: Adding to Sectors
12/14/2023 20:36:05: Connecting Portals, Spawners & ZSyncTransforms
ConnectPortals => Connected 7 portals.
ConnectSpawners => Connected 337 spawners and 602 'done' spawners.
12/14/2023 20:36:05: Loaded 9987 locations
12/14/2023 20:36:05: Unloading unused assets
Unloading 12 Unused Serialized files (Serialized files now loaded: 0)
The shader Hidden/Dof/DepthOfFieldHdr (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) is not supported on this platform!
The image effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) has been disabled as it's not supported on the current platform.
The shader Hidden/SunShaftsComposite (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) is not supported on this platform!
The shader Hidden/SimpleClear (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) is not supported on this platform!
The image effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) has been disabled as it's not supported on the current platform.
12/14/2023 20:36:05: Game server connected
Unloading 17 unused Assets to reduce memory usage. Loaded Objects now: 1726146.
Total: 529.294301 ms (FindLiveObjects: 215.890715 ms CreateObjectMapping: 55.580475 ms MarkObjects: 253.363358 ms  DeleteObjects: 4.458543 ms)

12/14/2023 20:36:08: Joined PlayFab Party network with ID "84e50e43-0b41-4294-afd8-fa9d78c8966c|AwA7K/pSrvXqT/hJza03AdIN6hmi2ldlc3RFdXJvcGUAAAAAAAAAAAAAyHiiEpapxSC+Owo1h8qJ5NuEOmtS0oeJqq8h6q5ybZZrbk9kbnMtaXIwLTgxZTUtZTVmYWZiMjYtNGNhOC00ZTVkLTlhNDktNDZmYjkyMmM2YzhlLndlc3RldXJvcGUuY2xvdWRhcHAuYXp1cmUuY29t"
12/14/2023 20:36:08: Created PlayFab lobby with ID "f81719e5-4f22-4bca-a2b1-d71a5b9ddc57.r-20230509", ConnectionString "cv2:f81719e5-4f22-4bca-a2b1-d71a5b9ddc57.r-20230509|451107|kv1:cA8iv2geTUIgl4fubn4ad4K7JlI/X7Y8omy1oG1a1vQ=" and owned by "14C4E5C9D5EBB55C"

```

**Comment by spannerman79** [comment] 2023-12-16 04:32
Duplicate of https://github.com/mbround18/valheim-docker/discussions/721

**Comment by mbround18** [comment] 2023-12-18 17:08
@Gengar-sama have you had an opportunity to review #721  ?

**Comment by Gengar-sama** [comment] 2023-12-20 09:47
> @Gengar-sama have you had an opportunity to review #721  ?

I have thank you, this is now resolved, thank you very much for the assistance.

**Comment by spannerman79** [comment] 2023-12-20 22:44
@Gengar-sama then close issue as resolved please.

**Comment by mbround18** [comment] 2023-12-26 23:40
Resolved

**Closed by mbround18** 2023-12-26 23:40 UTC
